name: Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Tfsec
      uses: aquasecurity/tfsec-pr-commenter-action@main
      with:
        {% raw -%}
        github_token: ${{ github.token }}
        {%- endraw %}
