repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_tfsec

- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.16.0
  hooks:
    - id: terraform-docs-go
      args: ["."]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
