formatter: markdown

sections:
  sections:
  show:
    - inputs
    - outputs
    - providers
    - modules

output:
  file: "README.md"
  mode: inject
  template: |-
    <!--- BEGIN_TF_DOCS --->
    {%- raw %}
    {{ .Content }}
    {% endraw -%}
    <!--- END_TF_DOCS --->
